// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  usersSidebar: [{type: "autogenerated", dirName: "users"}],
  pluginsSidebar: [{type: "autogenerated", dirName: "plugins"}],
  themesSidebar: [{type: "autogenerated", dirName: "themes"}],
  apiSidebar: [{type: "autogenerated", dirName: "api"}],
  discordSidebar: [{type: "autogenerated", dirName: "discord"}],
};