// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  usersSidebar: [{type: "autogenerated", dirName: "users"}],
  developersSidebar: [{type: "autogenerated", dirName: "developers"}],
  pluginsSidebar: [{type: "autogenerated", dirName: "plugins"}],
  themesSidebar: [{type: "autogenerated", dirName: "themes"}],
  apiSidebar: [{type: "autogenerated", dirName: "api"}],
  discordSidebar: [{type: "autogenerated", dirName: "discord"}],
  homeSidebar: [
    {type: "ref", id: "index", label: "Home"},
    {type: "ref", id: "users/index", label: "User Documentation"},
    {type: "ref", id: "developers/index", label: "Developer Documentation"},
    {type: "ref", id: "plugins/index", label: "Plugin Guides"},
    {type: "ref", id: "themes/index", label: "Theme Guides"},
    {type: "ref", id: "api/index", label: "Plugin API"},
    {type: "ref", id: "discord/index", label: "Discord Reference"}
  ]
};