// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  generalSidebar: [{type: "autogenerated", dirName: "general"}],
  pluginsSidebar: [{type: "autogenerated", dirName: "plugins"}],
  themesSidebar: [{type: "autogenerated", dirName: "themes"}],
};